### ISSUE TITLE
Support rails 5.x

### ISSUE THREAD

**Issue by gordcorp** [sunitparekh/data-anonymization#37]
I'm interested using this gem in a Rails 5 project.

**Comment by sunitparekh** [comment]
Thank you for your interest in library. I am also planning to upgrade to rails 5 in near future. However, I recommend that you keep data Anonymization project separate from your main project otherwise it adds up unwanted libraries and might run into dependency issues like rails 5. Keeping it separate will be easy long run.

**Comment by sunitparekh** [comment]
@bjgordon I have created a branch rails5, can you please give it a try and let me know if looking good or not. If all good, I will release new version.

**Comment by bjgordon** [comment]
Thanks @sunitparekh. I don't get any dependency errors anymore, and it seems to be running without errors, but I'm still learning how to use the gem. I'll try to look at it more next week.

**Comment by sunitparekh** [comment]
upgraded to rails5
